import { DEMO_ACCOUNTS } from "@/lib/static"

export const demoTaxRate = 0.092

export const demoOrganization = {
  id: "org-ngc",
  name: "Neighborhood Golf Carts",
  legalName: "Neighborhood Golf Carts LLC",
  slug: "ngc",
  phone: "985-402-1206",
  email: "contact@ngcgolfcarts.com",
  website: "https://ngcgolfcarts.com",
  primaryColor: "#2563eb",
  timezone: "America/Chicago",
  taxRate: demoTaxRate,
}

export const demoLocation = {
  id: "loc-covington",
  organizationId: demoOrganization.id,
  name: "Covington Shop",
  addressLine1: "71363 Thelma Ln",
  addressLine2: "Suite E",
  city: "Covington",
  state: "LA",
  postalCode: "70433",
  phone: demoOrganization.phone,
}

export const demoUsers = DEMO_ACCOUNTS.map((account, index) => ({
  id: `user-${index + 1}`,
  organizationId: demoOrganization.id,
  name: account.name,
  email: account.email,
  role: account.role,
  label: account.label,
  active: true,
}))

const customerBase = [
  {
    id: "cust-bayou-1",
    displayName: "Bayou Oaks HOA",
    companyName: "Bayou Oaks HOA",
    firstName: "Megan",
    lastName: "Landry",
    email: "operations@bayouoaks.example",
    phone: "985-555-0140",
    tags: ["HOA", "Fleet", "Priority"],
    portalToken: "demo-portal",
    address: ["124 Fairway Loop", "", "Covington", "LA", "70433"],
  },
  {
    id: "cust-chen-1",
    displayName: "Avery Chen",
    companyName: null,
    firstName: "Avery",
    lastName: "Chen",
    email: "avery.chen@example.com",
    phone: "985-555-0177",
    tags: ["Lithium lead", "Club Car"],
    portalToken: "portal-avery-chen",
    address: ["88 Live Oak Trace", "", "Mandeville", "LA", "70448"],
  },
  {
    id: "cust-stone-creek",
    displayName: "Stone Creek Club",
    companyName: "Stone Creek Club",
    firstName: "Drew",
    lastName: "Boudreaux",
    email: "facilities@stonecreek.example",
    phone: "985-555-0124",
    tags: ["Commercial", "Fleet"],
    portalToken: "portal-stone-creek",
    address: ["301 Clubhouse Dr", "", "Covington", "LA", "70433"],
  },
  {
    id: "cust-rodriguez-1",
    displayName: "Sofia Rodriguez",
    companyName: null,
    firstName: "Sofia",
    lastName: "Rodriguez",
    email: "sofia.rodriguez@example.com",
    phone: "504-555-0182",
    tags: ["Southshore", "Pickup fee"],
    portalToken: "portal-sofia-rodriguez",
    address: ["42 Pelican St", "", "Metairie", "LA", "70005"],
  },
  {
    id: "cust-carter-1",
    displayName: "Noah Carter",
    companyName: null,
    firstName: "Noah",
    lastName: "Carter",
    email: "noah.carter@example.com",
    phone: "985-555-0165",
    tags: ["Repair", "EZGO"],
    portalToken: "portal-noah-carter",
    address: ["612 Pine Hollow Rd", "", "Abita Springs", "LA", "70420"],
  },
  {
    id: "cust-magnolia",
    displayName: "Magnolia Ridge Rentals",
    companyName: "Magnolia Ridge Rentals",
    firstName: "Tessa",
    lastName: "Guidry",
    email: "tessa@magnoliaridge.example",
    phone: "985-555-0109",
    tags: ["Commercial", "Future sales"],
    portalToken: "portal-magnolia-ridge",
    address: ["517 Marina Blvd", "", "Madisonville", "LA", "70447"],
  },
  {
    id: "cust-wallace-1",
    displayName: "Elliot Wallace",
    companyName: null,
    firstName: "Elliot",
    lastName: "Wallace",
    email: "elliot.wallace@example.com",
    phone: "985-555-0113",
    tags: ["Yamaha", "Battery issue"],
    portalToken: "portal-elliot-wallace",
    address: ["218 Cypress Bend", "", "Slidell", "LA", "70458"],
  },
  {
    id: "cust-harper-1",
    displayName: "Harper Family",
    companyName: null,
    firstName: "Grace",
    lastName: "Harper",
    email: "grace.harper@example.com",
    phone: "985-555-0191",
    tags: ["Repeat customer", "Accessories"],
    portalToken: "portal-harper-family",
    address: ["76 Heron Ct", "", "Covington", "LA", "70435"],
  },
]

export const demoCustomers = customerBase.map((customer, index) => ({
  id: customer.id,
  organizationId: demoOrganization.id,
  displayName: customer.displayName,
  companyName: customer.companyName,
  firstName: customer.firstName,
  lastName: customer.lastName,
  email: customer.email,
  phone: customer.phone,
  tags: customer.tags,
  portalToken: customer.portalToken,
  lifetimeValue: [18420, 5275, 12240, 4988, 1390, 8600, 745, 2205][index],
  createdAt: `2026-0${Math.min(index + 1, 6)}-0${(index % 8) + 1}T14:00:00.000Z`,
  addresses: [
    {
      id: `addr-${customer.id}`,
      customerId: customer.id,
      label: "Primary",
      line1: customer.address[0],
      line2: customer.address[1],
      city: customer.address[2],
      state: customer.address[3],
      postalCode: customer.address[4],
      isPrimary: true,
    },
  ],
  contacts: [
    {
      id: `contact-${customer.id}`,
      customerId: customer.id,
      firstName: customer.firstName,
      lastName: customer.lastName,
      email: customer.email,
      phone: customer.phone,
      isPrimary: true,
    },
  ],
}))

export const demoEquipment = [
  {
    id: "eq-bayou-1",
    customerId: "cust-bayou-1",
    name: "HOA Patrol Cart 1",
    type: "Golf Cart",
    year: 2019,
    make: "Club Car",
    model: "Tempo",
    serialNumber: "CC19-BAYOU-01",
    batteryVoltage: "48V",
    powertrain: "Lead-acid",
  },
  {
    id: "eq-bayou-2",
    customerId: "cust-bayou-1",
    name: "HOA Patrol Cart 2",
    type: "Golf Cart",
    year: 2020,
    make: "Club Car",
    model: "Onward",
    serialNumber: "CC20-BAYOU-02",
    batteryVoltage: "48V",
    powertrain: "Lithium",
  },
  {
    id: "eq-chen-1",
    customerId: "cust-chen-1",
    name: "Chen family cart",
    type: "Golf Cart",
    year: 2018,
    make: "Club Car",
    model: "Precedent",
    serialNumber: "CC18-CHEN",
    batteryVoltage: "48V",
    powertrain: "Lead-acid",
  },
  {
    id: "eq-stone-1",
    customerId: "cust-stone-creek",
    name: "Range runner",
    type: "Golf Cart",
    year: 2021,
    make: "EZGO",
    model: "RXV",
    serialNumber: "EZ21-STONE",
    batteryVoltage: "48V",
    powertrain: "Lithium",
  },
  {
    id: "eq-rodriguez-1",
    customerId: "cust-rodriguez-1",
    name: "Rodriguez cart",
    type: "Golf Cart",
    year: 2017,
    make: "Yamaha",
    model: "Drive2",
    serialNumber: "YA17-SR",
    batteryVoltage: "48V",
    powertrain: "Lead-acid",
  },
  {
    id: "eq-carter-1",
    customerId: "cust-carter-1",
    name: "Carter EZGO",
    type: "Golf Cart",
    year: 2016,
    make: "EZGO",
    model: "TXT",
    serialNumber: "EZ16-NC",
    batteryVoltage: "36V",
    powertrain: "Lead-acid",
  },
  {
    id: "eq-magnolia-1",
    customerId: "cust-magnolia",
    name: "Rental cart A",
    type: "Golf Cart",
    year: 2022,
    make: "Club Car",
    model: "Tempo",
    serialNumber: "CC22-MAG-A",
    batteryVoltage: "48V",
    powertrain: "Lithium",
  },
  {
    id: "eq-wallace-1",
    customerId: "cust-wallace-1",
    name: "Wallace Yamaha",
    type: "Golf Cart",
    year: 2015,
    make: "Yamaha",
    model: "Drive",
    serialNumber: "YA15-EW",
    batteryVoltage: "48V",
    powertrain: "Lead-acid",
  },
  {
    id: "eq-harper-1",
    customerId: "cust-harper-1",
    name: "Harper neighborhood cart",
    type: "Golf Cart",
    year: 2023,
    make: "Evolution",
    model: "Classic 4",
    serialNumber: "EV23-HF",
    batteryVoltage: "48V",
    powertrain: "Lithium",
  },
]

export const demoBays = [
  { id: "bay-1", organizationId: demoOrganization.id, name: "Bay 1", status: "BUSY", currentWorkOrderId: "wo-1005" },
  { id: "bay-2", organizationId: demoOrganization.id, name: "Bay 2", status: "BUSY", currentWorkOrderId: "wo-1006" },
  { id: "bay-3", organizationId: demoOrganization.id, name: "Bay 3", status: "OPEN", currentWorkOrderId: null },
  { id: "bay-qc", organizationId: demoOrganization.id, name: "QC Lane", status: "BUSY", currentWorkOrderId: "wo-1007" },
]

export const demoLineItems = [
  { id: "li-wo-1001-1", parentId: "wo-1001", description: "Diagnostic minimum", quantity: 1, unitPrice: 179, taxable: true, total: 179 },
  { id: "li-wo-1002-1", parentId: "wo-1002", description: "48V Professional lithium conversion kit", quantity: 1, unitPrice: 4695, taxable: true, total: 4695 },
  { id: "li-wo-1002-2", parentId: "wo-1002", description: "Conversion labor and programming", quantity: 1, unitPrice: 650, taxable: false, total: 650 },
  { id: "li-wo-1004-1", parentId: "wo-1004", description: "Brake inspection and adjustment", quantity: 1, unitPrice: 225, taxable: false, total: 225 },
  { id: "li-wo-1005-1", parentId: "wo-1005", description: "36V Professional lithium conversion kit", quantity: 1, unitPrice: 3995, taxable: true, total: 3995 },
  { id: "li-wo-1006-1", parentId: "wo-1006", description: "Controller troubleshooting", quantity: 2, unitPrice: 125, taxable: false, total: 250 },
  { id: "li-wo-1007-1", parentId: "wo-1007", description: "QC road test and delivery prep", quantity: 1, unitPrice: 95, taxable: false, total: 95 },
  { id: "li-wo-1008-1", parentId: "wo-1008", description: "Accessory install bundle", quantity: 1, unitPrice: 460, taxable: true, total: 460 },
  { id: "li-wo-1009-1", parentId: "wo-1009", description: "Preventive maintenance package", quantity: 1, unitPrice: 389, taxable: true, total: 389 },
  { id: "li-wo-1010-1", parentId: "wo-1010", description: "Battery cable set", quantity: 1, unitPrice: 129, taxable: true, total: 129 },
]

export const demoWorkOrders = [
  {
    id: "wo-1001",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1001",
    customerId: "cust-bayou-1",
    equipmentId: "eq-bayou-1",
    title: "Intermittent power loss",
    concern: "Cart loses power near the back nine gate after 20 minutes of driving.",
    status: "RECEIVED",
    priority: 2,
    bayId: null,
    assignedUserId: "user-4",
    subtotal: 179,
    tax: 16.47,
    total: 195.47,
    scheduledStart: "2026-07-13T15:00:00.000Z",
    promisedAt: "2026-07-15T21:00:00.000Z",
    createdAt: "2026-07-12T14:45:00.000Z",
    updatedAt: "2026-07-13T13:10:00.000Z",
    checklist: ["Intake photos", "Battery voltage capture", "Controller scan"],
  },
  {
    id: "wo-1002",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1002",
    customerId: "cust-chen-1",
    equipmentId: "eq-chen-1",
    title: "48V lithium conversion",
    concern: "Customer approved lithium upgrade pending final signature.",
    status: "AWAITING_APPROVAL",
    priority: 1,
    bayId: null,
    assignedUserId: "user-2",
    subtotal: 5345,
    tax: 431.94,
    total: 5776.94,
    scheduledStart: "2026-07-14T14:00:00.000Z",
    promisedAt: "2026-07-18T21:00:00.000Z",
    createdAt: "2026-07-10T16:10:00.000Z",
    updatedAt: "2026-07-13T14:25:00.000Z",
    checklist: ["Estimate sent", "Battery tray measured", "Charger location confirmed"],
  },
  {
    id: "wo-1003",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1003",
    customerId: "cust-stone-creek",
    equipmentId: "eq-stone-1",
    title: "Fleet cart diagnosis",
    concern: "Range runner has charger fault and reduced top speed.",
    status: "DIAGNOSIS",
    priority: 2,
    bayId: null,
    assignedUserId: "user-4",
    subtotal: 179,
    tax: 16.47,
    total: 195.47,
    scheduledStart: "2026-07-13T18:00:00.000Z",
    promisedAt: "2026-07-16T21:00:00.000Z",
    createdAt: "2026-07-11T19:35:00.000Z",
    updatedAt: "2026-07-13T15:05:00.000Z",
    checklist: ["Charger test", "Speed sensor test"],
  },
  {
    id: "wo-1004",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1004",
    customerId: "cust-rodriguez-1",
    equipmentId: "eq-rodriguez-1",
    title: "Brake parts wait",
    concern: "Soft pedal and squeal on downhill braking.",
    status: "AWAITING_PARTS",
    priority: 3,
    bayId: null,
    assignedUserId: "user-4",
    subtotal: 225,
    tax: 0,
    total: 225,
    scheduledStart: "2026-07-15T14:00:00.000Z",
    promisedAt: "2026-07-19T20:00:00.000Z",
    createdAt: "2026-07-09T17:20:00.000Z",
    updatedAt: "2026-07-13T12:45:00.000Z",
    checklist: ["Parts ordered", "Customer notified"],
  },
  {
    id: "wo-1005",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1005",
    customerId: "cust-carter-1",
    equipmentId: "eq-carter-1",
    title: "36V lithium conversion",
    concern: "Replace aging lead-acid pack with Professional 36V kit.",
    status: "IN_PROGRESS",
    priority: 2,
    bayId: "bay-1",
    assignedUserId: "user-4",
    subtotal: 3995,
    tax: 367.54,
    total: 4362.54,
    scheduledStart: "2026-07-13T13:00:00.000Z",
    promisedAt: "2026-07-16T21:00:00.000Z",
    createdAt: "2026-07-08T15:00:00.000Z",
    updatedAt: "2026-07-13T16:15:00.000Z",
    checklist: ["Old pack removed", "Tray cleaned", "BMS mount in progress"],
  },
  {
    id: "wo-1006",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1006",
    customerId: "cust-magnolia",
    equipmentId: "eq-magnolia-1",
    title: "Controller troubleshooting",
    concern: "Rental cart surges under load.",
    status: "IN_PROGRESS",
    priority: 1,
    bayId: "bay-2",
    assignedUserId: "user-4",
    subtotal: 250,
    tax: 0,
    total: 250,
    scheduledStart: "2026-07-13T14:30:00.000Z",
    promisedAt: "2026-07-14T21:00:00.000Z",
    createdAt: "2026-07-12T16:20:00.000Z",
    updatedAt: "2026-07-13T16:35:00.000Z",
    checklist: ["Controller scan", "Load test"],
  },
  {
    id: "wo-1007",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1007",
    customerId: "cust-bayou-1",
    equipmentId: "eq-bayou-2",
    title: "QC after service",
    concern: "Final road test after lithium maintenance and accessory check.",
    status: "QUALITY_CHECK",
    priority: 3,
    bayId: "bay-qc",
    assignedUserId: "user-4",
    subtotal: 95,
    tax: 0,
    total: 95,
    scheduledStart: "2026-07-13T17:00:00.000Z",
    promisedAt: "2026-07-13T22:00:00.000Z",
    createdAt: "2026-07-07T15:30:00.000Z",
    updatedAt: "2026-07-13T16:50:00.000Z",
    checklist: ["Torque check", "Road test", "Photo closeout"],
  },
  {
    id: "wo-1008",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1008",
    customerId: "cust-harper-1",
    equipmentId: "eq-harper-1",
    title: "Ready for pickup",
    concern: "Accessory install complete; customer picking up this afternoon.",
    status: "READY_FOR_PICKUP",
    priority: 4,
    bayId: null,
    assignedUserId: "user-2",
    subtotal: 460,
    tax: 42.32,
    total: 502.32,
    scheduledStart: "2026-07-12T13:00:00.000Z",
    promisedAt: "2026-07-13T21:00:00.000Z",
    createdAt: "2026-07-06T18:45:00.000Z",
    updatedAt: "2026-07-13T15:40:00.000Z",
    checklist: ["Customer text sent", "Invoice ready"],
  },
  {
    id: "wo-1009",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1009",
    customerId: "cust-wallace-1",
    equipmentId: "eq-wallace-1",
    title: "Ready for delivery",
    concern: "Preventive maintenance complete; delivery route assigned.",
    status: "READY_FOR_DELIVERY",
    priority: 3,
    bayId: null,
    assignedUserId: "user-6",
    subtotal: 389,
    tax: 35.79,
    total: 424.79,
    scheduledStart: "2026-07-11T15:00:00.000Z",
    promisedAt: "2026-07-13T23:00:00.000Z",
    createdAt: "2026-07-05T14:00:00.000Z",
    updatedAt: "2026-07-13T14:50:00.000Z",
    checklist: ["Delivery photos", "Invoice link sent"],
  },
  {
    id: "wo-1010",
    organizationId: demoOrganization.id,
    locationId: demoLocation.id,
    number: "WO-1010",
    customerId: "cust-stone-creek",
    equipmentId: "eq-stone-1",
    title: "Cable replacement complete",
    concern: "Replaced corroded cable set and returned cart to fleet.",
    status: "COMPLETED",
    priority: 4,
    bayId: null,
    assignedUserId: "user-4",
    subtotal: 129,
    tax: 11.87,
    total: 140.87,
    scheduledStart: "2026-07-08T14:00:00.000Z",
    promisedAt: "2026-07-10T21:00:00.000Z",
    createdAt: "2026-07-03T16:00:00.000Z",
    updatedAt: "2026-07-10T20:05:00.000Z",
    checklist: ["Closeout complete", "Invoice paid"],
  },
]

export const demoEstimates = [
  {
    id: "est-2001",
    organizationId: demoOrganization.id,
    number: "EST-2001",
    customerId: "cust-chen-1",
    workOrderId: "wo-1002",
    status: "VIEWED",
    subtotal: 5345,
    tax: 431.94,
    total: 5776.94,
    expiresAt: "2026-07-20T23:59:00.000Z",
    createdAt: "2026-07-12T15:00:00.000Z",
    updatedAt: "2026-07-13T14:20:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1002"),
  },
  {
    id: "est-2002",
    organizationId: demoOrganization.id,
    number: "EST-2002",
    customerId: "cust-carter-1",
    workOrderId: "wo-1005",
    status: "APPROVED",
    subtotal: 3995,
    tax: 367.54,
    total: 4362.54,
    expiresAt: "2026-07-18T23:59:00.000Z",
    createdAt: "2026-07-09T15:00:00.000Z",
    updatedAt: "2026-07-11T17:30:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1005"),
  },
  {
    id: "est-2003",
    organizationId: demoOrganization.id,
    number: "EST-2003",
    customerId: "cust-rodriguez-1",
    workOrderId: "wo-1004",
    status: "SENT",
    subtotal: 225,
    tax: 0,
    total: 225,
    expiresAt: "2026-07-22T23:59:00.000Z",
    createdAt: "2026-07-12T18:30:00.000Z",
    updatedAt: "2026-07-12T18:30:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1004"),
  },
  {
    id: "est-2004",
    organizationId: demoOrganization.id,
    number: "EST-2004",
    customerId: "cust-bayou-1",
    workOrderId: "wo-1001",
    status: "DRAFT",
    subtotal: 179,
    tax: 16.47,
    total: 195.47,
    expiresAt: "2026-07-25T23:59:00.000Z",
    createdAt: "2026-07-13T13:20:00.000Z",
    updatedAt: "2026-07-13T13:20:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1001"),
  },
]

export const demoInvoices = [
  {
    id: "inv-3001",
    organizationId: demoOrganization.id,
    number: "INV-3001",
    customerId: "cust-harper-1",
    workOrderId: "wo-1008",
    status: "SENT",
    subtotal: 460,
    tax: 42.32,
    total: 502.32,
    amountPaid: 0,
    amountDue: 502.32,
    dueDate: "2026-07-20T23:59:00.000Z",
    createdAt: "2026-07-13T15:50:00.000Z",
    updatedAt: "2026-07-13T15:50:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1008"),
  },
  {
    id: "inv-3002",
    organizationId: demoOrganization.id,
    number: "INV-3002",
    customerId: "cust-wallace-1",
    workOrderId: "wo-1009",
    status: "PARTIALLY_PAID",
    subtotal: 389,
    tax: 35.79,
    total: 424.79,
    amountPaid: 200,
    amountDue: 224.79,
    dueDate: "2026-07-18T23:59:00.000Z",
    createdAt: "2026-07-13T14:55:00.000Z",
    updatedAt: "2026-07-13T16:00:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1009"),
  },
  {
    id: "inv-3003",
    organizationId: demoOrganization.id,
    number: "INV-3003",
    customerId: "cust-stone-creek",
    workOrderId: "wo-1010",
    status: "PAID",
    subtotal: 129,
    tax: 11.87,
    total: 140.87,
    amountPaid: 140.87,
    amountDue: 0,
    dueDate: "2026-07-17T23:59:00.000Z",
    createdAt: "2026-07-10T20:10:00.000Z",
    updatedAt: "2026-07-11T13:10:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1010"),
  },
  {
    id: "inv-3004",
    organizationId: demoOrganization.id,
    number: "INV-3004",
    customerId: "cust-bayou-1",
    workOrderId: "wo-1007",
    status: "OVERDUE",
    subtotal: 95,
    tax: 0,
    total: 95,
    amountPaid: 0,
    amountDue: 95,
    dueDate: "2026-07-12T23:59:00.000Z",
    createdAt: "2026-07-08T18:00:00.000Z",
    updatedAt: "2026-07-13T13:00:00.000Z",
    lineItems: demoLineItems.filter((item) => item.parentId === "wo-1007"),
  },
]

export const demoVehicles = [
  { id: "veh-1", name: "NGC Pickup Truck", type: "Truck", plate: "NGC-101", capacity: "1 cart", status: "READY" },
  { id: "veh-2", name: "NGC Enclosed Trailer", type: "Trailer", plate: "NGC-202", capacity: "2 carts", status: "READY" },
]

export const demoDispatches = [
  {
    id: "disp-4001",
    workOrderId: "wo-1001",
    customerId: "cust-bayou-1",
    type: "PICKUP",
    status: "SCHEDULED",
    driverUserId: "user-5",
    vehicleId: "veh-1",
    scheduledAt: "2026-07-13T15:30:00.000Z",
    windowStart: "2026-07-13T15:00:00.000Z",
    windowEnd: "2026-07-13T17:00:00.000Z",
    fee: 0,
    notes: "Gate code in customer notes. Free Northshore pickup.",
  },
  {
    id: "disp-4002",
    workOrderId: "wo-1003",
    customerId: "cust-stone-creek",
    type: "PICKUP",
    status: "EN_ROUTE",
    driverUserId: "user-5",
    vehicleId: "veh-2",
    scheduledAt: "2026-07-13T18:00:00.000Z",
    windowStart: "2026-07-13T17:30:00.000Z",
    windowEnd: "2026-07-13T19:00:00.000Z",
    fee: 0,
    notes: "Facilities manager will meet at cart barn.",
  },
  {
    id: "disp-4003",
    workOrderId: "wo-1009",
    customerId: "cust-wallace-1",
    type: "DELIVERY",
    status: "ASSIGNED",
    driverUserId: "user-6",
    vehicleId: "veh-1",
    scheduledAt: "2026-07-13T21:30:00.000Z",
    windowStart: "2026-07-13T21:00:00.000Z",
    windowEnd: "2026-07-13T23:00:00.000Z",
    fee: 0,
    notes: "Collect signature and final balance.",
  },
  {
    id: "disp-4004",
    workOrderId: "wo-1004",
    customerId: "cust-rodriguez-1",
    type: "PICKUP",
    status: "SCHEDULED",
    driverUserId: "user-5",
    vehicleId: "veh-2",
    scheduledAt: "2026-07-14T14:30:00.000Z",
    windowStart: "2026-07-14T14:00:00.000Z",
    windowEnd: "2026-07-14T16:00:00.000Z",
    fee: 99,
    notes: "Southshore pickup fee applies.",
  },
  {
    id: "disp-4005",
    workOrderId: "wo-1008",
    customerId: "cust-harper-1",
    type: "PICKUP",
    status: "ARRIVED",
    driverUserId: null,
    vehicleId: null,
    scheduledAt: "2026-07-13T20:00:00.000Z",
    windowStart: "2026-07-13T20:00:00.000Z",
    windowEnd: "2026-07-13T21:00:00.000Z",
    fee: 0,
    notes: "Customer pickup at Covington shop.",
  },
  {
    id: "disp-4006",
    workOrderId: "wo-1010",
    customerId: "cust-stone-creek",
    type: "DELIVERY",
    status: "COMPLETED",
    driverUserId: "user-6",
    vehicleId: "veh-1",
    scheduledAt: "2026-07-10T20:30:00.000Z",
    windowStart: "2026-07-10T20:00:00.000Z",
    windowEnd: "2026-07-10T22:00:00.000Z",
    fee: 0,
    notes: "Returned to fleet barn.",
  },
]

export const demoPriceBookItems = [
  { id: "pb-diagnostic", name: "Diagnostic minimum", category: "Service", sku: "DIAG-179", price: 179, taxable: true, active: true },
  { id: "pb-lithium-36", name: "36V Professional lithium conversion kit", category: "Lithium", sku: "PRO-36V", price: 3995, taxable: true, active: true },
  { id: "pb-lithium-48", name: "48V Professional lithium conversion kit", category: "Lithium", sku: "PRO-48V", price: 4695, taxable: true, active: true },
  { id: "pb-lithium-mini", name: "MINI Professional lithium conversion kit", category: "Lithium", sku: "PRO-MINI", price: 2995, taxable: true, active: true },
  { id: "pb-lithium-72", name: "72V Professional lithium conversion kit", category: "Lithium", sku: "PRO-72V", price: 6495, taxable: true, active: true },
  { id: "pb-lithium-150", name: "150AH Professional lithium conversion kit", category: "Lithium", sku: "PRO-150AH", price: 6895, taxable: true, active: true },
  { id: "pb-labor", name: "Shop labor hour", category: "Labor", sku: "LABOR-HR", price: 125, taxable: false, active: true },
  { id: "pb-pickup-fee", name: "Pickup/delivery outside 40 mi or Southshore", category: "Dispatch", sku: "DISPATCH-99", price: 99, taxable: false, active: true },
]

export const demoInventory = [
  { id: "invitem-1", sku: "PRO-36V", name: "36V Professional lithium kit", category: "Lithium", onHand: 2, reserved: 1, reorderPoint: 1, unitCost: 2600 },
  { id: "invitem-2", sku: "PRO-48V", name: "48V Professional lithium kit", category: "Lithium", onHand: 4, reserved: 1, reorderPoint: 2, unitCost: 3100 },
  { id: "invitem-3", sku: "PRO-MINI", name: "MINI Professional lithium kit", category: "Lithium", onHand: 1, reserved: 0, reorderPoint: 1, unitCost: 2050 },
  { id: "invitem-4", sku: "PRO-72V", name: "72V Professional lithium kit", category: "Lithium", onHand: 1, reserved: 0, reorderPoint: 1, unitCost: 4500 },
  { id: "invitem-5", sku: "CABLE-48V", name: "48V cable set", category: "Electrical", onHand: 8, reserved: 2, reorderPoint: 4, unitCost: 58 },
  { id: "invitem-6", sku: "BRAKE-YAM-DR2", name: "Yamaha Drive2 brake kit", category: "Brakes", onHand: 0, reserved: 1, reorderPoint: 2, unitCost: 92 },
  { id: "invitem-7", sku: "CHARGER-48V", name: "48V smart charger", category: "Chargers", onHand: 3, reserved: 0, reorderPoint: 1, unitCost: 380 },
]

export const demoLeads = [
  { id: "lead-1", name: "Landon Miller", source: "Website", status: "NEW", interest: "48V lithium conversion", value: 5345, createdAt: "2026-07-13T13:00:00.000Z", nextStep: "Call by noon" },
  { id: "lead-2", name: "Northlake Marina", source: "Referral", status: "QUALIFIED", interest: "Fleet lithium review", value: 15900, createdAt: "2026-07-11T15:20:00.000Z", nextStep: "Send photo checklist" },
  { id: "lead-3", name: "Priya Shah", source: "Facebook", status: "ESTIMATE_SENT", interest: "MINI lithium kit", value: 2995, createdAt: "2026-07-09T18:45:00.000Z", nextStep: "Follow up tomorrow" },
  { id: "lead-4", name: "Riverbend HOA", source: "Google", status: "CONTACTED", interest: "Diagnostics for 3 carts", value: 537, createdAt: "2026-07-08T14:15:00.000Z", nextStep: "Schedule intake" },
  { id: "lead-5", name: "Ethan Brooks", source: "Walk-in", status: "WON", interest: "Accessory install", value: 460, createdAt: "2026-07-05T20:00:00.000Z", nextStep: "Converted to WO-1008" },
]

export const demoCommunications = [
  { id: "comm-1", customerId: "cust-chen-1", channel: "SMS", direction: "OUTBOUND", subject: "Estimate follow-up", body: "Your 48V lithium conversion estimate is ready to approve.", createdAt: "2026-07-13T14:22:00.000Z" },
  { id: "comm-2", customerId: "cust-wallace-1", channel: "SMS", direction: "OUTBOUND", subject: "Delivery reminder", body: "We are scheduled to deliver your cart between 4-6 PM.", createdAt: "2026-07-13T15:05:00.000Z" },
  { id: "comm-3", customerId: "cust-bayou-1", channel: "EMAIL", direction: "INBOUND", subject: "Gate code", body: "Use 1206# at the back gate.", createdAt: "2026-07-13T13:40:00.000Z" },
  { id: "comm-4", customerId: "cust-rodriguez-1", channel: "SMS", direction: "OUTBOUND", subject: "Parts update", body: "Brake parts are ordered; pickup is scheduled for tomorrow.", createdAt: "2026-07-13T12:55:00.000Z" },
]

export const demoTemplates = [
  { id: "tpl-1", name: "Lithium estimate follow-up", channel: "SMS", body: "Hi {{customer}}, your Professional lithium estimate is ready. Reply YES and we will reserve your install slot." },
  { id: "tpl-2", name: "Pickup window confirmation", channel: "SMS", body: "NGC pickup is scheduled for {{window}}. Please leave the cart accessible and charged if possible." },
  { id: "tpl-3", name: "Ready for pickup", channel: "SMS", body: "Your cart is ready at 71363 Thelma Ln, Suite E. We are open Mon-Fri 8-5." },
  { id: "tpl-4", name: "Invoice reminder", channel: "EMAIL", body: "Your NGC invoice is ready. Thank you for trusting Neighborhood Golf Carts." },
]

export function getDemoCustomer(id: string) {
  return demoCustomers.find((customer) => customer.id === id)
}

export function getDemoCustomerByPortalToken(token: string) {
  return demoCustomers.find((customer) => customer.portalToken === token)
}

export function getDemoEquipment(id: string) {
  return demoEquipment.find((equipment) => equipment.id === id)
}

export function getDemoWorkOrder(id: string) {
  return demoWorkOrders.find((workOrder) => workOrder.id === id)
}

export function getDemoEstimate(id: string) {
  return demoEstimates.find((estimate) => estimate.id === id)
}

export function getDemoInvoice(id: string) {
  return demoInvoices.find((invoice) => invoice.id === id)
}

export function getDemoDispatch(id: string) {
  return demoDispatches.find((dispatch) => dispatch.id === id)
}

export function getDemoUser(id: string) {
  return demoUsers.find((user) => user.id === id)
}

export function getDemoWorkOrdersForCustomer(customerId: string) {
  return demoWorkOrders.filter((workOrder) => workOrder.customerId === customerId)
}

export function getDemoEstimatesForCustomer(customerId: string) {
  return demoEstimates.filter((estimate) => estimate.customerId === customerId)
}

export function getDemoInvoicesForCustomer(customerId: string) {
  return demoInvoices.filter((invoice) => invoice.customerId === customerId)
}

export function getDemoEquipmentForCustomer(customerId: string) {
  return demoEquipment.filter((equipment) => equipment.customerId === customerId)
}

export function getDemoLineItems(parentId: string) {
  return demoLineItems.filter((item) => item.parentId === parentId)
}

export function getDemoDispatchesForWorkOrder(workOrderId: string) {
  return demoDispatches.filter((dispatch) => dispatch.workOrderId === workOrderId)
}
