import type { KpiDefinitionMeta } from './types'

/**
 * Registry of every KPI the DMS tracks (or can derive).
 * Adding a future KPI = append here + a case in compute.ts.
 */
export const KPI_REGISTRY: KpiDefinitionMeta[] = [
  // —— Executive ——
  {
    id: 'active-jobs',
    name: 'Active Jobs',
    shortDescription: 'Carts currently in the shop workflow',
    description: 'Open work orders not yet Ready or Picked Up.',
    formula: "COUNT(jobs WHERE status NOT IN ('ready','picked-up'))",
    historicalContext: 'Primary WIP signal for Ryan’s morning huddle.',
    category: 'executive',
    format: 'number',
    unit: 'jobs',
    direction: 'lower-better',
    defaultTarget: 12,
    defaultThresholds: { greenAt: 100, yellowAt: 80 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'technician'],
    source: 'jobs',
  },
  {
    id: 'shop-health',
    name: 'Shop Health Score',
    shortDescription: 'Composite of WIP, AR pressure, and completions',
    description:
      '0–100 score blending waitlist pressure, deposit alerts, and completion pace.',
    formula: 'weighted blend of waitlist, deposit alerts, completions vs target',
    historicalContext: 'Executive roll-up — green means the floor and office are in sync.',
    category: 'executive',
    format: 'number',
    unit: 'score',
    direction: 'higher-better',
    defaultTarget: 80,
    defaultThresholds: { greenAt: 100, yellowAt: 85 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'derived',
  },
  {
    id: 'customer-waitlist',
    name: 'Customer Waitlist',
    shortDescription: 'Carts in Received awaiting diagnosis',
    description: 'Jobs still in Received — the intake backlog.',
    formula: "COUNT(jobs WHERE status = 'received')",
    historicalContext: 'Whiteboard Intake lane cap is 3; sustained higher means schedule pressure.',
    category: 'executive',
    format: 'number',
    unit: 'carts',
    direction: 'lower-better',
    defaultTarget: 3,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'jobs',
  },

  // —— Financial ——
  {
    id: 'revenue-period',
    name: 'Completed Revenue',
    shortDescription: 'Estimated revenue on completed jobs in range',
    description: 'Sum of estimatedRevenue for picked-up jobs completed in the selected period.',
    formula: "SUM(estimatedRevenue) WHERE status='picked-up' AND completedAt in range",
    historicalContext: 'Cash-basis intent; QBO remains SoR for books (Griffin & Furman).',
    category: 'financial',
    format: 'currency',
    unit: '$',
    direction: 'higher-better',
    defaultTarget: 25000,
    defaultThresholds: { greenAt: 100, yellowAt: 75 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'jobs',
  },
  {
    id: 'outstanding-ar',
    name: 'Outstanding AR',
    shortDescription: 'Open invoice balances from HCP',
    description: 'Total outstanding balance across unpaid / partial invoices.',
    formula: 'invoicing.summary.outstandingTotal',
    historicalContext: 'Chase COLLECT_BALANCE and SCHEDULE_UNPAID alerts first.',
    category: 'financial',
    format: 'currency',
    unit: '$',
    direction: 'lower-better',
    defaultTarget: 15000,
    defaultThresholds: { greenAt: 100, yellowAt: 80 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },
  {
    id: 'collected-mtd',
    name: 'Collected (MTD)',
    shortDescription: 'Payments collected month-to-date',
    description: 'HCP collected amount MTD from invoicing summary.',
    formula: 'invoicing.summary.collectedMtd',
    historicalContext: 'Pairs with completed revenue to show cash conversion.',
    category: 'financial',
    format: 'currency',
    unit: '$',
    direction: 'higher-better',
    defaultTarget: 20000,
    defaultThresholds: { greenAt: 100, yellowAt: 75 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },
  {
    id: 'avg-invoice',
    name: 'Average Invoice',
    shortDescription: 'Mean invoice total',
    description: 'Average invoice amount from HCP invoicing payload.',
    formula: 'invoicing.summary.avgInvoiceAmount',
    historicalContext: 'Watch mix shift when lithium volume rises.',
    category: 'financial',
    format: 'currency',
    unit: '$',
    direction: 'higher-better',
    defaultTarget: 1200,
    defaultThresholds: { greenAt: 100, yellowAt: 85 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },
  {
    id: 'lithium-outstanding',
    name: 'Lithium Outstanding',
    shortDescription: 'Open balances on lithium jobs',
    description: 'Outstanding AR tagged as lithium conversions.',
    formula: 'invoicing.summary.lithiumOutstanding',
    historicalContext: 'Lithium deposits ($1,800) should clear before parts order.',
    category: 'financial',
    format: 'currency',
    unit: '$',
    direction: 'lower-better',
    defaultTarget: 5000,
    defaultThresholds: { greenAt: 100, yellowAt: 80 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },

  // —— Operations ——
  {
    id: 'completed-period',
    name: 'Jobs Completed',
    shortDescription: 'Picked-up completions in the selected range',
    description: 'Count of jobs marked picked-up with completedAt in range.',
    formula: "COUNT(jobs WHERE status='picked-up' AND completedAt in range)",
    historicalContext: 'Finish-list discipline at 8:15 drives this number.',
    category: 'operations',
    format: 'number',
    unit: 'jobs',
    direction: 'higher-better',
    defaultTarget: 8,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'technician'],
    source: 'jobs',
  },
  {
    id: 'avg-turnaround',
    name: 'Avg. Turnaround',
    shortDescription: 'Days from intake to pickup',
    description: 'Mean days between createdAt and completedAt for completed jobs in range (fallback: all-time).',
    formula: 'AVG(daysBetween(createdAt, completedAt)) for completed jobs',
    historicalContext: 'Lower is better — parts delays and waitlist drive spikes.',
    category: 'operations',
    format: 'days',
    unit: 'days',
    direction: 'lower-better',
    defaultTarget: 7,
    defaultThresholds: { greenAt: 100, yellowAt: 80 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'technician'],
    source: 'jobs',
  },
  {
    id: 'parts-on-order',
    name: 'Parts on Order',
    shortDescription: 'Active jobs waiting on parts language',
    description: 'Heuristic count from HCP extras (description/notes mention part/order).',
    formula: 'hcpMeta.extras.partsOnOrder',
    historicalContext: 'Not a true PO system — replace when inventory module ships.',
    category: 'operations',
    format: 'number',
    unit: 'jobs',
    direction: 'lower-better',
    defaultTarget: 4,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'extras',
  },
  {
    id: 'in-repair',
    name: 'In Repair',
    shortDescription: 'Carts actively being worked',
    description: "Jobs with status 'in-repair'.",
    formula: "COUNT(jobs WHERE status='in-repair')",
    historicalContext: 'Whiteboard In Repair lane — tech capacity signal.',
    category: 'operations',
    format: 'number',
    unit: 'carts',
    direction: 'higher-better',
    defaultTarget: 4,
    defaultThresholds: { greenAt: 80, yellowAt: 50 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'technician'],
    source: 'jobs',
  },
  {
    id: 'waiting-parts',
    name: 'Waiting Parts',
    shortDescription: 'Jobs blocked on parts',
    description: "Jobs with status 'waiting-parts'.",
    formula: "COUNT(jobs WHERE status='waiting-parts')",
    historicalContext: 'Should stay under Parts lane max (~4).',
    category: 'operations',
    format: 'number',
    unit: 'jobs',
    direction: 'lower-better',
    defaultTarget: 4,
    defaultThresholds: { greenAt: 100, yellowAt: 75 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'technician'],
    source: 'jobs',
  },
  {
    id: 'qa-queue',
    name: 'QC Queue',
    shortDescription: 'Jobs in QA awaiting sign-off',
    description: "Jobs with status 'qa'.",
    formula: "COUNT(jobs WHERE status='qa')",
    historicalContext: 'Whiteboard QC lane max 2 — techs should clear same day.',
    category: 'operations',
    format: 'number',
    unit: 'carts',
    direction: 'lower-better',
    defaultTarget: 2,
    defaultThresholds: { greenAt: 100, yellowAt: 50 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'technician'],
    source: 'jobs',
  },

  // —— Customer ——
  {
    id: 'open-invoices',
    name: 'Open Invoices',
    shortDescription: 'Invoices with remaining balance',
    description: 'Count of invoices still open in HCP AR.',
    formula: 'invoicing.summary.openInvoiceCount',
    historicalContext: 'Office follows up before delivery when balance remains.',
    category: 'customer',
    format: 'number',
    unit: 'invoices',
    direction: 'lower-better',
    defaultTarget: 25,
    defaultThresholds: { greenAt: 100, yellowAt: 80 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },
  {
    id: 'deposit-alerts',
    name: 'Deposit Alerts',
    shortDescription: 'Jobs needing deposit action',
    description: 'BLOCK_PARTS + SCHEDULE_UNPAID + COLLECT_BALANCE alerts.',
    formula: 'invoicing.summary.depositAlertCount',
    historicalContext: 'Work BLOCK_PARTS before ordering lithium/battery parts.',
    category: 'customer',
    format: 'number',
    unit: 'alerts',
    direction: 'lower-better',
    defaultTarget: 3,
    defaultThresholds: { greenAt: 100, yellowAt: 60 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },
  {
    id: 'ready-for-pickup',
    name: 'Ready for Pickup',
    shortDescription: 'Carts in Ready lane',
    description: "Jobs with status 'ready' awaiting customer or Roy delivery.",
    formula: "COUNT(jobs WHERE status='ready')",
    historicalContext: 'Ready max ~4; notify customer / schedule Roy.',
    category: 'customer',
    format: 'number',
    unit: 'carts',
    direction: 'higher-better',
    defaultTarget: 3,
    defaultThresholds: { greenAt: 80, yellowAt: 40 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'driver'],
    source: 'jobs',
  },

  // —— Team ——
  {
    id: 'my-active-jobs',
    name: 'My Active Jobs',
    shortDescription: 'Jobs assigned to you that are still open',
    description: 'Personal WIP for the signed-in technician.',
    formula: "COUNT(jobs WHERE assignedTech = session.name AND status not ready/picked-up)",
    historicalContext: 'Techs should keep personal WIP manageable for QC quality.',
    category: 'team',
    format: 'number',
    unit: 'jobs',
    direction: 'lower-better',
    defaultTarget: 3,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['technician'],
    personal: true,
    source: 'jobs',
  },
  {
    id: 'my-completed',
    name: 'My Completions',
    shortDescription: 'Your picked-up jobs in the selected range',
    description: 'Personal completion count for the signed-in technician.',
    formula: "COUNT(assigned jobs picked-up in range)",
    historicalContext: 'Pairs with QC discipline — finish clean, then Ready.',
    category: 'team',
    format: 'number',
    unit: 'jobs',
    direction: 'higher-better',
    defaultTarget: 3,
    defaultThresholds: { greenAt: 100, yellowAt: 60 },
    accessRoles: ['technician'],
    personal: true,
    source: 'jobs',
  },
  {
    id: 'tech-utilization',
    name: 'Logged Labor Hours',
    shortDescription: 'Hours from Agent Input time logs in range',
    description: 'Sum of time-log submission hours in the selected period.',
    formula: "SUM(time-log.hours) WHERE submittedAt in range",
    historicalContext: 'Only as good as shop logging — encourage techs to use Input.',
    category: 'team',
    format: 'decimal',
    unit: 'hrs',
    direction: 'higher-better',
    defaultTarget: 30,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['owner', 'service-manager', 'technician'],
    source: 'submissions',
  },
  {
    id: 'assigned-coverage',
    name: 'Assignment Coverage',
    shortDescription: '% of open jobs with a tech assigned',
    description: 'Share of active jobs that have assignedTech set.',
    formula: 'assigned active / active jobs × 100',
    historicalContext: 'Ryan assigns from Board — unassigned carts stall the floor.',
    category: 'team',
    format: 'percent',
    unit: '%',
    direction: 'higher-better',
    defaultTarget: 95,
    defaultThresholds: { greenAt: 100, yellowAt: 85 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'jobs',
  },
  {
    id: 'agent-activity',
    name: 'Shop Log Activity',
    shortDescription: 'Agent Input submissions in range',
    description: 'Count of local Agent Input submissions in the period.',
    formula: 'COUNT(submissions WHERE timestamp in range)',
    historicalContext: 'Proxy for shop communication hygiene.',
    category: 'team',
    format: 'number',
    unit: 'logs',
    direction: 'higher-better',
    defaultTarget: 20,
    defaultThresholds: { greenAt: 100, yellowAt: 50 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'technician'],
    source: 'submissions',
  },

  // —— Fleet / Driver ——
  {
    id: 'deliveries-period',
    name: 'Deliveries / Pickups Done',
    shortDescription: 'Completed handoffs in range (proxy)',
    description: 'Picked-up jobs completed in range — proxy for customer/Roy handoffs.',
    formula: "COUNT(picked-up in range)",
    historicalContext: 'Until route tracking exists, completions approximate delivery volume.',
    category: 'fleet',
    format: 'number',
    unit: 'trips',
    direction: 'higher-better',
    defaultTarget: 6,
    defaultThresholds: { greenAt: 100, yellowAt: 60 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'driver'],
    source: 'jobs',
  },
  {
    id: 'out-today',
    name: 'Out Today Queue',
    shortDescription: 'Ready carts awaiting delivery/pickup',
    description: 'Same as Ready lane — driver focus list.',
    formula: "COUNT(status='ready')",
    historicalContext: 'Whiteboard Out Today lane — Roy’s morning route source.',
    category: 'fleet',
    format: 'number',
    unit: 'carts',
    direction: 'higher-better',
    defaultTarget: 2,
    defaultThresholds: { greenAt: 80, yellowAt: 40 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'driver'],
    source: 'jobs',
  },
  {
    id: 'fleet-accounts',
    name: 'Fleet Accounts',
    shortDescription: 'Commercial / fleet customers on file',
    description: 'Distinct commercial customers from HCP extras.',
    formula: 'hcpMeta.extras.fleetAccounts',
    historicalContext: 'Growth lever once service ops are stable.',
    category: 'fleet',
    format: 'number',
    unit: 'accounts',
    direction: 'higher-better',
    defaultTarget: 8,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['owner', 'service-manager', 'front-desk', 'driver'],
    source: 'extras',
  },
  {
    id: 'on-time-delivery',
    name: 'On-Time Delivery Rate',
    shortDescription: 'Placeholder until route timestamps exist',
    description:
      'Mock/fallback metric — replace when driver route check-ins capture ETA vs actual.',
    formula: 'mock until route timestamps are logged',
    historicalContext: 'Driver Route SOP checklist is the interim process control.',
    category: 'fleet',
    format: 'percent',
    unit: '%',
    direction: 'higher-better',
    defaultTarget: 95,
    defaultThresholds: { greenAt: 100, yellowAt: 90 },
    accessRoles: ['owner', 'service-manager', 'driver'],
    source: 'mock',
  },

  // —— Growth ——
  {
    id: 'new-jobs-period',
    name: 'New Jobs',
    shortDescription: 'Jobs created in the selected range',
    description: 'Intake volume — jobs with createdAt in range.',
    formula: 'COUNT(jobs WHERE createdAt in range)',
    historicalContext: 'Pairs with waitlist — surge without capacity grows backlog.',
    category: 'growth',
    format: 'number',
    unit: 'jobs',
    direction: 'higher-better',
    defaultTarget: 10,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'jobs',
  },
  {
    id: 'paid-invoices',
    name: 'Paid Invoices',
    shortDescription: 'Fully paid invoice count',
    description: 'HCP paid invoice count (point-in-time from sync).',
    formula: 'invoicing.summary.paidInvoiceCount',
    historicalContext: 'Trailing indicator of collections success.',
    category: 'growth',
    format: 'number',
    unit: 'invoices',
    direction: 'higher-better',
    defaultTarget: 50,
    defaultThresholds: { greenAt: 100, yellowAt: 70 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },

  // —— Compliance ——
  {
    id: 'block-parts',
    name: 'Block-Parts Alerts',
    shortDescription: 'Jobs blocked from ordering parts',
    description: 'Deposit alerts with code BLOCK_PARTS.',
    formula: 'invoicing.summary.blockPartsCount',
    historicalContext: 'Policy: no lithium/battery parts without deposit.',
    category: 'compliance',
    format: 'number',
    unit: 'alerts',
    direction: 'lower-better',
    defaultTarget: 1,
    defaultThresholds: { greenAt: 100, yellowAt: 50 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'invoicing',
  },
  {
    id: 'deposit-compliance',
    name: 'Deposit Gate Compliance',
    shortDescription: '% of deposit-required jobs with gap cleared',
    description: 'Among jobs with requiredDeposit > 0, share with depositGap <= 0.',
    formula: '1 - (jobs with depositGap>0 / jobs with requiredDeposit>0)',
    historicalContext: 'Enforced in Jobs/Board — manager override only.',
    category: 'compliance',
    format: 'percent',
    unit: '%',
    direction: 'higher-better',
    defaultTarget: 95,
    defaultThresholds: { greenAt: 100, yellowAt: 85 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'jobs',
  },
  {
    id: 'low-stock-alerts',
    name: 'Low-Stock Alerts',
    shortDescription: 'Inventory reorder flags (placeholder)',
    description: 'From HCP extras — currently 0 until inventory module is live.',
    formula: 'hcpMeta.extras.lowStockAlerts',
    historicalContext: 'Placeholder KPI — keep visible so the hub stays ready for inventory.',
    category: 'compliance',
    format: 'number',
    unit: 'alerts',
    direction: 'lower-better',
    defaultTarget: 0,
    defaultThresholds: { greenAt: 100, yellowAt: 50 },
    accessRoles: ['owner', 'service-manager', 'front-desk'],
    source: 'extras',
  },
]

export function getKpiMeta(id: string): KpiDefinitionMeta | undefined {
  return KPI_REGISTRY.find((k) => k.id === id)
}
