import type { GuideStep } from './types'

/**
 * Interactive learning path for the NGC Operations Dashboard.
 * Steps navigate + spotlight UI so Ryan / Christine can learn by doing.
 */
export const GUIDE_STEPS: GuideStep[] = [
  {
    id: 'welcome',
    chapter: 'Start here',
    title: 'Welcome to the NGC Dashboard',
    body: 'This is your shop operating system — live jobs from Housecall Pro, KPIs, intake, SOPs, QC, invoicing, and more. This Guide walks every screen with you. Use Next / Back anytime, or open Guide from the menu to jump chapters.',
    tip: 'Progress is saved on this device. Restart anytime from Guide → Restart.',
    route: '/',
    target: 'guide-welcome',
  },
  {
    id: 'nav-overview',
    chapter: 'Start here',
    title: 'How to move around',
    body: 'On a phone: bottom tabs for daily work, More for the full menu. On desktop: the left sidebar lists every module. Your login role controls what you see (owner, front desk, tech, driver).',
    tip: 'Tap More (⋯) on mobile to open the full list — including this Guide.',
    route: '/',
    target: 'guide-nav',
    openDrawer: true,
  },
  {
    id: 'home-overview',
    chapter: 'Home Dashboard',
    title: 'Home — your morning snapshot',
    body: 'Home is the daily overview: shop KPIs, sync status, active jobs, revenue trend, pinned manuals, and recent agent activity. Start here each morning before the huddle.',
    tip: 'Pull down on any page (or tap the refresh icon) to reload HCP shop data.',
    route: '/',
    target: 'guide-page-title',
    moduleId: 'dashboard',
  },
  {
    id: 'home-range',
    chapter: 'Home Dashboard',
    title: 'Today / Week / Month filter',
    body: 'Use these buttons to change the time window for dashboard metrics. Today for the huddle, This Week for throughput, This Month for revenue pace.',
    route: '/',
    target: 'guide-date-range',
    moduleId: 'dashboard',
  },
  {
    id: 'home-sync',
    chapter: 'Home Dashboard',
    title: 'HCP sync banner',
    body: 'The banner shows whether you are on live Housecall Pro data, a Pages cache, or local DMS. If numbers look stale, tap Refresh. Morning Sync also updates GitHub Pages automatically.',
    tip: 'Amber/red means data is missing or overdue — fix sync before quoting numbers.',
    route: '/',
    target: 'guide-hcp-sync',
    moduleId: 'dashboard',
  },
  {
    id: 'home-kpis',
    chapter: 'Home Dashboard',
    title: 'Key metrics cards',
    body: 'Quick KPIs: Active Jobs, Completed This Week, Revenue MTD, Avg Turnaround, Parts on Order, Low Stock, Waitlist, Fleet Accounts. Tap Active Jobs or Waitlist to jump to Jobs.',
    tip: 'For deeper finance & ops KPIs with targets, use KPI Hub — not just these cards.',
    route: '/',
    target: 'guide-kpi-cards',
    moduleId: 'dashboard',
  },
  {
    id: 'home-jobs-revenue',
    chapter: 'Home Dashboard',
    title: 'Revenue + Active Jobs',
    body: 'Revenue Trend charts closed work. Active Jobs lists carts currently in the shop (techs only see their assignments). Use View all → to open the full Jobs list.',
    route: '/',
    target: 'guide-home-panels',
    moduleId: 'dashboard',
  },
  {
    id: 'intake',
    chapter: 'Customer Intake',
    title: 'Customer Intake — new leads',
    body: 'Log new leads with customer/cart details, photos, waitlist notes, and estimate status. Follow the intake SOP steps on the form so nothing is skipped before a cart hits the shop.',
    tip: 'Office / owners: use Intake for every new call or walk-in lead. Techs typically do not see this module.',
    route: '/intake',
    target: 'guide-page-title',
    moduleId: 'intake',
  },
  {
    id: 'sops',
    chapter: 'SOPs',
    title: 'SOP library',
    body: 'Browse standard operating procedures grouped by section. Open any SOP for steps, checklists, and related links. Access is role-filtered — owners and Christine see the full library; shop/drivers see what they need.',
    tip: 'Deposit-gate SOPs stay owner/office-only. Add custom SOPs later from Settings.',
    route: '/sops',
    target: 'guide-page-title',
    moduleId: 'sops',
  },
  {
    id: 'kpi-hub',
    chapter: 'KPI Hub',
    title: 'KPI Hub — scoreboard',
    body: 'Role-based metrics with targets, status colors, and date ranges (Today → YTD). Tap a card for detail. Export CSV or print/PDF for Friday weekly review.',
    tip: 'Owners see finance + ops packs. Use this for weekly review — not just Home KPIs.',
    route: '/kpi-hub',
    target: 'guide-page-title',
    moduleId: 'kpi-hub',
  },
  {
    id: 'resources',
    chapter: 'Manuals & Files',
    title: 'Manuals & reference files',
    body: 'Service manuals, wiring diagrams, parts catalogs, vendor docs, and warranty info. Pin favorites so they appear on Home. Search and filter by category.',
    tip: 'Club Car Precedent PDFs and Drive manuals live here — open from the shop floor phone.',
    route: '/resources',
    target: 'guide-page-title',
    moduleId: 'resources',
  },
  {
    id: 'jobs',
    chapter: 'Jobs',
    title: 'Repair Jobs list',
    body: 'All repair orders you can access. Filter by status. Owners/managers can create jobs and assign techs. Techs see assigned work only. Open a job to edit status, notes, and details.',
    tip: 'Writable on device (browser) or via local DMS API when running the full stack.',
    route: '/jobs',
    target: 'guide-page-title',
    moduleId: 'jobs',
  },
  {
    id: 'board',
    chapter: 'Status Board',
    title: 'Shop Status Board',
    body: 'Kanban view of WIP: Received → Diagnosing → Waiting Parts → In Repair → QA → Ready. Drag the shop mentally against WIP target (aim ≤6 in progress). Tap a card to edit.',
    tip: 'Use with the physical whiteboard at the 8:15 huddle — digital board mirrors HCP/DMS state.',
    route: '/board',
    target: 'guide-page-title',
    moduleId: 'board',
  },
  {
    id: 'qc',
    chapter: 'QC Form',
    title: 'QC completion form',
    body: 'Technicians complete shop QC before marking ready for pickup. Walk each checklist section, confirm lithium/care items when relevant, then save. Pick a job from the list or open via /qc/:jobId.',
    tip: 'QC is tech-focused. Office roles use Jobs/Board to confirm ready status instead.',
    route: '/qc',
    target: 'guide-page-title',
    moduleId: 'qc',
  },
  {
    id: 'agent-input',
    chapter: 'Agent Input',
    title: 'Agent Input — shop updates',
    body: 'Log repairs, status changes, parts used, time, and notes. Choose who is submitting, pick or create a job link, and submit. Updates feed Home activity and the Jobs board.',
    tip: 'Best for techs mid-job. Prefer Jobs/Board status edits when you are already on a work order.',
    route: '/agent-input',
    target: 'guide-page-title',
    moduleId: 'agent-input',
  },
  {
    id: 'invoicing',
    chapter: 'Invoicing',
    title: 'Invoicing & deposits',
    body: 'AR snapshot from Housecall Pro: open balances, deposit alerts, revenue categories, and invoice list. Christine uses Deposit Alerts to gate work until deposits clear.',
    tip: 'Lithium deposits are policy — do not waive. Cross-check with Live Ops deposit alerts in Command Center.',
    route: '/invoicing',
    target: 'guide-page-title',
    moduleId: 'invoicing',
  },
  {
    id: 'settings',
    chapter: 'Settings',
    title: 'Settings & integrations',
    body: 'Business profile, staff roles/passcodes, custom SOPs, Google Drive manuals how-to, HCP import status, and QuickBooks Online connection. Owners manage staff access here.',
    tip: 'Bookkeeper: Griffin & Furman, LLC. On GitHub Pages, import/QBO may show as cache mode until the API server is running.',
    route: '/settings',
    target: 'guide-page-title',
    moduleId: 'settings',
  },
  {
    id: 'coming-soon',
    chapter: 'Roadmap',
    title: 'Coming soon modules',
    body: 'Inventory, Customers (CRM), and Scheduling appear in the menu as Soon. Use Customer Intake for leads today; keep parts and appointments in HCP/QBO until those modules ship.',
    tip: 'Track build priority in Command Center → Build Pipeline / improvement backlog.',
    route: '/',
    target: 'guide-nav',
    openDrawer: true,
  },
  {
    id: 'finish',
    chapter: 'Finish',
    title: 'You are ready to run the shop',
    body: 'Daily rhythm: Home + Board in the morning → Intake/Jobs through the day → QC before pickup → Invoicing/deposits with Christine → KPI Hub on Friday. Re-open this Guide anytime from the sidebar, More menu, or the Guide button.',
    tip: 'Bookmark https://ngc4160.github.io/NGC-Brain/ on your phone home screen for one-tap access.',
    route: '/',
    target: 'guide-launcher',
  },
]

export function chaptersFromSteps(steps: GuideStep[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const s of steps) {
    if (!seen.has(s.chapter)) {
      seen.add(s.chapter)
      out.push(s.chapter)
    }
  }
  return out
}
